# Generated by Django 3.0.8 on 2020-07-26 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nemail',
            new_name='email',
        ),
    ]
